#!/bin/sh

if ! cd /var/db/freebsd-update; then
  echo "WHAT?!" >&2
  exit 1
fi

for file in [0-9a-f]*.gz; do
  if [ -f "$file" ]; then
    break
  else
    echo "No files to process." >&2
    exit 0
  fi
done

# Yes, we're ParsingLs.  You'll survive.
ls -f | grep '^[0-9a-f]\{64\}\.gz$' | while read file; do

  if [ ! -f "$file" ]; then
    echo "That was unexpected.  What is '$file'?" >&2
    exit 1
  fi

  [ "$file" != "$(zcat $file | sha256).gz" ] && rm "$file" && echo ">>> $file FAILED (removed)"

done

