#!/usr/bin/awk -f

# See also: https://tools.ietf.org/html/rfc4180

BEGIN {
  r=0
  OFS=FS=","
  #print "> ARG1=" ARGV[1]; exit 1
}

function fcwarning() {
    printf "ERROR: field count does not match in %s(%d) ... YMMV.\n", FILENAME, FNR > "/dev/stderr"
}

/\r$/ { $0 = substr($0,0,length($0)-1) }

FNR==1 {
  if (NR>1 && NF != length(h)) fcwarning()
  delete h
  for (i=1; i<=NF; i++) {
    h[i]=$i
  }
  next
}

{
  if (NF != length(h)) fcwarning()
  r++
  for (i=1; i<=NF; i++) {
    output[r,h[i]]=$i
  }
}

END {
  sep=""
  for (i=1; i<=length(h); i++) {
    printf "%s%s", sep, h[i]
    sep=OFS
  }
  printf "%s", ORS
  for (o=1; o<=r; o++) {
    sep=""
    for (i=1; i<=length(h); i++) {
      printf "%s%s", sep, output[o,h[i]]
      sep=OFS
    }
    printf "%s", ORS
  }
}

