#!/usr/local/bin/bash
#
# $Id: mailqgrep,v 1.7 2011/02/24 01:54:37 paul Exp paul $

if [ "$1" = "-p" ]; then
	Pretty=true
	shift
elif [ "$MAILQGREP" = "-p" ]; then
	Pretty=true
else
	Pretty=false
fi

if echo "$1" | egrep -q '^[0-9]-[0-9]+$'; then
	lhs="${1%%-*}"
	rhs="${1##*-}"
	range="$[ $rhs - $lhs + 1 ]"
	if [ -f /var/log/maillog.$1.bz2 ]; then
		ext=".bz2"
		cmd="bzgrep"
	elif [ -f /var/log/maillog.$1.gz ]; then
		ext=".gz"
		cmd="zgrep"
	elif [ -f /var/log/maillog.$1 ]; then
		ext=""
		cmd="grep"
	else
		echo "ERROR: no maillog!" >&2
		ls -l /var/log/maillog.${1}* | sed 's/^/	/' >&2
		exit 1
	fi
	cmd="$cmd -hv spamd"
	for i in `jot $range $lhs` ; do
		cmd="$cmd /var/log/maillog.${i}${ext}"
	done
	search="$2"
	shift
elif echo "$1" | egrep -q '^[0-9]+$'; then
	if [ -f /var/log/maillog.$1.bz2 ]; then
		ext=".bz2"
		cmd="bzgrep"
	elif [ -f /var/log/maillog.$1.gz ]; then
		ext=".gz"
		cmd="zgrep"
	elif [-f /var/log/maillog.$1 ]; then
		ext=""
		cmd="grep"
	else
		echo "ERROR: no file found" >&2
		exit 1
	fi
	cmd="$cmd -v spamd /var/log/maillog.${1}${ext}"
	search="$2"
	shift
else
	cmd="grep -v spamd /var/log/maillog"
	search="$1"
fi

if [ -z "$search" ]; then
	printf 'NO SEARCH STRING\n'
	printf "\nUsage: `basename $0` [-p] [daterange] searchstring\n\n"
	printf "where daterange is blank for the current day, 0 for yesterday,\n"
	printf "1 for the day before, etc.\n\n"
	printf "Including the -p option will make output 'pretty'.\n\n"
	exit 1
fi

#echo ">> cmd = $cmd" >&2
string="`$cmd | egrep \"$search\" | awk '{print $6}' | sort -u | awk '{a = a \"|\" $1} END {print substr(a,2);}'`"

if [ -z "$string" ]; then
	printf 'NO RECORDS FOUND\n'
	exit 1
fi

if $Pretty; then
	pfilter='s/: (from|to)/\
	\1/;s/, (msgid|relay|mailer|stat)=/,\
	\1=/g;p'
else
	pfilter='p'
fi

printf '\nSEARCH = "%s"' "$search"
printf '\nSTRING = "%s"\n' "$string"
printf '\n'
$cmd | egrep "$string" | uniq | sed -nE "$pfilter"
printf '\n'

