#!/usr/bin/awk -f

function nrmlz(mac,     i,a,o) {
	if (tolower(mac) !~ /^[0-9a-f]{1,2}(:[0-9a-f]{1,2}){5}$/) return "<" mac ">"
	split(mac,a,":")
	o=""
	for (i=1;i<=6;i++) {
		o=sprintf("%s:%02s", o, a[i])
	}
	gsub(/ /,"0",o)		# some awks don't provide leading zeros on %s
	return tolower(substr(o,2))
}

BEGIN {

	#print nrmlz("a:b:c:D:e:F")
	#print nrmlz("000:1:2:3:4:5")

	while (getline < "/etc/ethers") {
		macs[nrmlz($1)]=$2
	}

	if (!system("test -t 0")) {
		em="\033[1m"; no="\033[0m"
	} else {
		em=""; no=""
	}
	close(cmd)

	while ("arp -an" | getline) {
		mac=nrmlz($4)
		if (mac in macs) {
			$4=sprintf("%s(%s%s%s)", mac, em, macs[mac], no)
			$4=sprintf("(%s%s%s)%s", em, macs[mac], no, mac)
		} else
		if (/incomplete/) {
			continue
		}
		print
	}

}

