#!/bin/bash

SOAfile="$1"
err=""
if [ -z "$SOAfile" ]; then
  err="No file specified"
elif [ ! -e "$SOAfile" ]; then
  err="File not found"
fi
if [ -n "$err" ]; then
  printf 'ERROR: %s\n' "$err" >&2
  exit 1
fi

read line soa < <(awk -v field=6 '/^@/ { if($2=="IN"){field++} for(i=1;i<field;i++){if(i==NF){field=field-NF;getline;i=1}} print NR,$field}' $SOAfile)

newsoa=$(date '+%Y%m%d00')

while [ "$newsoa" -le "$soa" ]; do
	newsoa=$((newsoa + 1))
done

if sed -i.bak "${line}s/$soa/$newsoa/" "$SOAfile"; then
	printf "%s: %s -> %s\n" "$SOAfile" "$soa" "$newsoa"
fi

