#!/usr/bin/env bash

# Add the following to /etc/asterisk/voicemail.conf:
#
#	[general]
#	externpasscheck=/usr/local/bin/voicemailpasswordcheck
#
# Then place this script ... well, you know where.

mailbox="$1"; context="$2"; oldpass="$3"; newpass="$4" 

minlength=4

logfile="/var/log/asterisk/${0##*/}.log"

unset why

if [ "$newpass" = "$oldpass" ]; then
  status="INVALID"
  why="passwords must be different"
elif [ "$newpass" = 1234 ]; then
  status="INVALID"
  why="are you serious?"
elif [ "${#newpass}" -lt $minlength ]; then
  status="INVALID"
  why="password must be at least $minlength characters long"
elif [[ 01234567890123456789098765432109876543210 == *"$newpass"* ]]; then
  status="INVALID"
  why="password is a straight, you lose"
elif echo "$newpass" | grep -q '\(.\)\1\1'; then
  status="INVALID"
  why="same digit tripled"
elif echo "$newpass" | grep -q '^\(..*\)\1\1*$'; then
  status="INVALID"
  why="pattern repeated"
elif echo "$newpass" | grep -q '\(.\)\(.\)\2\1'; then
  status="INVALID"
  why="2-digit pattern reversed"
elif echo "$newpass" | grep -q '\(.\)\(.\)\(.\)\3\2\1'; then
  status="INVALID"
  why="3-digit pattern reversed"
else
  status="VALID"
  why="ok"
fi

echo "$status"

# Note: log file must exist and be writable if you want to record logs.
if [ -w "$logfile" ]; then
  printf "%s mailbox=%s context=%s status=%s (%s)\n" "$(date '+[%Y-%m-%d %H:%M:%S]')" "$mailbox" "$context" "$status" "$why" >> "$logfile"
fi

