#!/usr/bin/env bash

# Add the following to /etc/asterisk/voicemail.conf:
#
#	[general]
#	externpasscheck=/usr/local/bin/voicemailpasswordcheck
#
# Then place this script ... well, you know where.

# The following tests are available. Adjust or comment out whatever you please.
#
diffpass=true		# Require new password to be different from old one.
minlength=4		# Minimum length. 4 is probably too short for safety.
straight=true		# Numbers all in a row, fronwards or backwards.
tripledigit=true	# A single digit repeated twice anywhere in the password.
repeatedpattern=true	# Any repeated multi-digit pattern.
reversed2=true		# Any reversed 2-digit pattern, i.e. 12321
#reversed3=true		# Any reversed 3-digit pattern, i.e. 123321

logfile="/var/log/asterisk/${0##*/}.log"

#################################
# You probably don't want to edit anything below this
# point unless you plan to submit a pull request.
#################################

mailbox="$1"; context="$2"; oldpass="$3"; newpass="$4" 

unset why

if [ "$newpass" = 1234 ]; then
  status="INVALID"
  why="are you serious?"
elif ${diffpass:-false} && [ "$newpass" = "$oldpass" ]; then
  status="INVALID"
  why="passwords must be different"
elif [ "${#newpass}" -lt $minlength ]; then
  status="INVALID"
  why="password must be at least $minlength characters long"
elif ${straight:-false} && [[ 012345678901234567890 == *"$newpass"* ]]; then
  status="INVALID"
  why="password is a straight, you lose"
elif ${straight:-false} && [[ 098765432109876543210 == *"$newpass"* ]]; then
  status="INVALID"
  why="password is a descending straight, you lose"
elif ${tripledigit:-false} && echo "$newpass" | grep -q '\(.\)\1\1'; then
  status="INVALID"
  why="same digit tripled"
elif ${repeatedpattern:-false} && echo "$newpass" | grep -q '^\(..*\)\1\1*$'; then
  status="INVALID"
  why="pattern repeated"
elif ${reversed2:-false} && echo "$newpass" | grep -q '\(.\)\(.\)\2\1'; then
  status="INVALID"
  why="2-digit pattern reversed"
elif ${reversed3:-false} && echo "$newpass" | grep -q '\(.\)\(.\)\(.\)\3\2\1'; then
  status="INVALID"
  why="3-digit pattern reversed"
else
  status="VALID"
  why="ok"
fi

echo "$status"

# Note: log file must exist and be writable if you want to record logs.
if [ -w "$logfile" ]; then
  printf "%s mailbox=%s context=%s status=%s (%s)\n" "$(date '+[%Y-%m-%d %H:%M:%S]')" "$mailbox" "$context" "$status" "$why" >> "$logfile"
fi

