#!/usr/bin/env bash

usage() {
  echo ""
  echo "Usage: ${0##*/} dataset"
  echo ""
  echo "Once running, you can nagivate using:"
  echo "  j  next pair"
  echo "  k  previous pair"
  echo "  l  display a list of snapshots"
  echo "  g  go to a specific point in the list"
  echo "  q  quit"
  echo ""
}

if [ -z "$1" ]; then
  usage
  exit 1
elif ! zfs list -Ho name "$1" >/dev/null; then
  exit 1
elif ! zfs list -t snapshot -rHo name | grep -q "^$1@"; then
  echo "cannot diff '$1': dataset has no snapshots" >&2
  exit 1
fi

snaps=($(zfs list -t snapshot -rHo name -d 1 "$1"))

if [ ${#snaps[@]} -eq 1 ]; then
  zfs diff "${snaps[0]}"
  exit $?
fi

echo "Browsing ${#snaps[@]} snapshots..."
for ((i=0;i<${#snaps[@]};i++)); do
  printf "(%d) %s\n" "$i" "${snaps[$i]}"
done

lhs=0
while :; do
  echo ">> ($lhs) zfs diff \"${snaps[$lhs]}\" \"${snaps[$((lhs+1))]}\""
  zfs diff "${snaps[$lhs]}" "${snaps[$((lhs+1))]}"
  choice=""
  while :; do
    read -s -n 1 -p "(j/k/g/l/q)? " choice
    echo ""
    case "$choice" in
      q) break 2 ;;
      j) ((lhs++)) ;;
      k) ((lhs--)) ;;
      g) read -p "Jump to (0-$((${#snaps[@]} - 1))): " go
         if [ "$go" = 0 ] || [[ "$go" =~ ^[0-9]+$ ]]; then
           lhs=$go
         fi
         ;;
      l) for ((i=0;i<${#snaps[@]};i++)); do
           printf "(%d) %s\n" "$i" "${snaps[$i]}"
         done
         ;&
      *) continue ;;
    esac
    break
  done
  case "$lhs" in
    -1) lhs=0 ;;
    ${#snaps[@]}) break ;;
  esac
done

